In [22]:
from automate_Muhammad_Taufiqurrahman import preprocess_data
import pandas as pd

df = pd.read_csv("Telco-Customer-Churn.csv")
hasil = preprocess_data(df)
print("\n✅ Data hasil preprocessing (5 baris pertama):")

=== 🚀 AUTOMATED PREPROCESSING PIPELINE ===

📍 Menangani Missing Values...
✅ Penanganan missing values selesai.

📍 Menghapus Data Duplikat...
Tidak ditemukan data duplikat.


📍 Normalisasi & Standarisasi Fitur...
✅ Normalisasi dan standarisasi selesai.

📍 Deteksi dan Penanganan Outlier...
✅ Outlier selesai ditangani.

📍 Encoding Data Kategorikal...
✅ Encoding selesai.

📍 Melakukan Binning Data Numerik...
✅ Binning selesai.

🎯 Semua tahapan preprocessing selesai.
Data siap digunakan untuk pelatihan model.


✅ Data hasil preprocessing (5 baris pertama):

In [23]:
hasil['cleaned'].head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0.0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0.0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0.0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0.0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0.0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [24]:
hasil['normalized'].head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0.0,Yes,No,0.013889,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,0.115423,29.85,No
1,5575-GNVDE,Male,0.0,No,No,0.472222,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,0.385075,1889.5,No
2,3668-QPYBK,Male,0.0,No,No,0.027778,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,0.354229,108.15,Yes
3,7795-CFOCW,Male,0.0,No,No,0.625000,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),0.239303,1840.75,No
4,9237-HQITU,Female,0.0,No,No,0.027778,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,0.521891,151.65,Yes

In [25]:
hasil['standardized'].head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,-0.439916,Yes,No,-1.277445,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,-1.160323,29.85,No
1,5575-GNVDE,Male,-0.439916,No,No,0.066327,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,-0.259629,1889.5,No
2,3668-QPYBK,Male,-0.439916,No,No,-1.236724,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,-0.362660,108.15,Yes
3,7795-CFOCW,Male,-0.439916,No,No,0.514251,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),-0.746535,1840.75,No
4,9237-HQITU,Female,-0.439916,No,No,-1.236724,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,0.197365,151.65,Yes

In [26]:
hasil['encoded'].head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,...,StreamingMovies_No,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0.000142,0,0.0,1,0,1,0,1,29.85,0.000142,...,True,False,False,True,False,False,False,False,True,False
1,0.000142,1,0.0,0,0,34,1,0,56.95,0.000142,...,True,False,False,False,True,False,False,False,False,True
2,0.000142,1,0.0,0,0,2,1,1,53.85,0.000142,...,True,False,False,True,False,False,False,False,False,True
3,0.000142,1,0.0,0,0,45,0,0,42.30,0.000142,...,True,False,False,False,True,False,True,False,False,False
4,0.000142,0,0.0,0,0,2,1,1,70.70,0.000142,...,True,False,False,True,False,False,False,False,True,False

In [27]:
hasil['binned'].head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,...,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,tenure_bin_width,tenure_bin_freq,MonthlyCharges_bin_width,MonthlyCharges_bin_freq
0,0.000142,0,0.0,1,0,1,0,1,29.85,0.000142,...,False,False,False,False,True,False,Rendah,Rendah,Rendah,Rendah
1,0.000142,1,0.0,0,0,34,1,0,56.95,0.000142,...,True,False,False,False,False,True,Sedang,Sedang,Sedang,Sedang
2,0.000142,1,0.0,0,0,2,1,1,53.85,0.000142,...,False,False,False,False,False,True,Rendah,Rendah,Sedang,Sedang
3,0.000142,1,0.0,0,0,45,0,0,42.30,0.000142,...,True,False,True,False,False,False,Sedang,Sedang,Rendah,Rendah
4,0.000142,0,0.0,0,0,2,1,1,70.70,0.000142,...,False,False,False,False,True,False,Rendah,Rendah,Sedang,Sedang